[workspace]
resolver = "2"
members = [
    "f-biski64",
    "f-pbiski64",
    "f-file",
    "f-hex",
    "f-limit",
    "f-peek",
    "f-pqxo64",
    "f-reduce",
    "f-sirius64",
    "f-qxo64",
    "f-xoshiro",
    "f-pcg",
    "qxo64",
    "seedy64",
    "speedy64",
    "s-entropy",
    "s-file",
    "s-file-loop",
    "s-seedier64",
    "s-seedy64-reset",
    "s-seedy64",
    "s-speedy64",
    "s-zeros",
    "softrng",
    "t-bits",
    "t-hole",
    "t-nist-quick",
    "t-nist-all",
    "timer-profile",
]
