[workspace]
resolver = "2"
members = [
    "f-biski64",
    "f-file",
    "f-hex",
    "f-limit",
    "f-peek",
    "f-pqxo64",
    "f-qxo64",
    "f-xoshiro",
    "f-pcg",
    "pqxo64",
    "qxo64",
    "seedy64",
    "s-entropy",
    "s-file",
    "s-seedy64-reset",
    "s-seedy64",
    "s-zeros",
    "softrng",
    "t-hole",
    "t-bits",
    "timer-profile",
]
